app/controllers/anp_controller.py
# import requests

# def fetch_anp_data():
#     api_key = "M7QrsxD6Uza4APeLAQtEXiAg4ZmPGpdPuFwVodah"
#     url = ("https://api.eia.gov/v2/petroleum/pri/spt/data/"
#            "?frequency=monthly&data[0]=value&start=2019-01&end=2024-06"
#            "&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
#            f"&api_key={api_key}")

#     try:
#         response = requests.get(url)
#         data = response.json()
        
#         # Verifica se os dados foram retornados corretamente
#         if 'response' in data and 'data' in data['response']:
#             # Filtra os dados pelo 'product-name' igual a "UK Brent Crude Oil"
#             filtered_data = [item for item in data['response']['data'] if item['product-name'] == "UK Brent Crude Oil"]
#             # # Imprime os dados filtrados para inspeção
#             # print("Dados filtrados:")
#             # for item in filtered_data:
#             #     print(item)

#             return filtered_data
#         else:
#             print("Falha ao buscar dados da ANP")
#             return []
#     except Exception as e:
#         print(f"Erro ao buscar dados da API ANP: {e}")
#         return []

import requests
from app.models import BrentANP, db

def fetch_anp_data():
    api_key = "M7QrsxD6Uza4APeLAQtEXiAg4ZmPGpdPuFwVodah"
    url = ("https://api.eia.gov/v2/petroleum/pri/spt/data/"
           "?frequency=monthly&data[0]=value&start=2019-01&end=2024-06"
           "&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
           f"&api_key={api_key}")

    try:
        response = requests.get(url)
        data = response.json()
        
        if 'response' in data and 'data' in data['response']:
            filtered_data = [item for item in data['response']['data'] if item['product-name'] == "UK Brent Crude Oil"]
            return filtered_data
        else:
            print("Falha ao buscar dados da ANP")
            return []
    except Exception as e:
        print(f"Erro ao buscar dados da API ANP: {e}")
        return []

def save_anp_data(app):
    with app.app_context():
        data = fetch_anp_data()
        for item in data:
            # Transformar o período de 'YYYY-MM' para 'MM-YYYY'
            original_period = item['period']
            transformed_period = f"{original_period[5:]}-{original_period[:4]}"
            
            if not BrentANP.query.filter_by(period=transformed_period).first():
                new_entry = BrentANP(
                    period=transformed_period,
                    product=item['product'],
                    product_name=item['product-name'],
                    value=item['value'],
                    units=item['units']
                )
                db.session.add(new_entry)
                db.session.commit()
                print(f"Dados salvos: {new_entry}")
            else:
                print(f"Dados para o período {transformed_period} já existem.")

app/routes.py
from flask import Blueprint, render_template, request,send_from_directory, current_app,redirect,url_for
from app.controllers.siconfi_controller import fetch_siconfi_RREO_data, fetch_siconfi_RGF_data
from app import db
# from app.models import SiconfiDataRREO, SiconfiDataRGF
from datetime import datetime
import pytz
import os
from app.controllers.anp_controller import fetch_anp_data
from app.controllers.ibge_controller import fetch_ipca_data, fetch_unemployment_data, download_caged_data
from app.utils.web_scraper import download_next_focus_report, convert_all_pdfs
from werkzeug.utils import secure_filename
from app.controllers.focus_controller import fetch_selic_data, fetch_pib_data, fetch_focus_ipca_data, fetch_focus_cambio_data
from flask_login import login_required


main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
@login_required
def upload_siconfi():
    if request.method == 'POST':
        if 'file' not in request.files:
            return 'Nenhum arquivo selecionado', 400

        file = request.files['file']

        if file.filename == '':
            return 'Nenhum arquivo selecionado', 400

        if file:
            # Salva o arquivo no diretório da área de trabalho do usuário atual
            filename = secure_filename(file.filename)
            desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')

            # Determine o diretório de upload com base no nome do arquivo
            if "finbraRREO" in filename:
                upload_folder = os.path.join(desktop_path, 'uploads', 'rreo')
            elif "finbraRGF" in filename:
                upload_folder = os.path.join(desktop_path, 'uploads', 'rgf')
            elif "FER" in filename:
                if "Rentabilidade" in filename:
                    upload_folder = os.path.join(desktop_path, 'uploads', 'fer_rentabilidade')
                elif "Patrimonio" in filename:
                    upload_folder = os.path.join(desktop_path, 'uploads', 'fer_patrimonio')
                else:
                    return 'Nome de arquivo não reconhecido para FER', 400
            elif 'UFF' in filename:
                upload_folder = os.path.join(desktop_path, 'uploads', 'uff')
            else:
                return 'Nome de arquivo não reconhecido', 400

            # Cria o diretório se não existir
            if not os.path.exists(upload_folder):
                try:
                    os.makedirs(upload_folder)
                except Exception as e:
                    current_app.logger.error(f"Erro ao criar o diretório: {e}")
                    return f"Erro ao criar o diretório: {e}", 500

            file_path = os.path.join(upload_folder, filename)

            try:
                file.save(file_path)
                current_app.logger.info(f"Arquivo salvo em: {file_path}")

                # Chama o controlador apropriado com base no nome do arquivo
                if 'rreo' in file_path:
                    from app.controllers.siconfi_controller import save_rreo_data_to_db
                    save_rreo_data_to_db(current_app, file_path)
                elif 'rgf' in file_path:
                    from app.controllers.siconfi_controller import save_rgf_data_to_db
                    save_rgf_data_to_db(current_app, file_path)
                elif 'fer_rentabilidade' in file_path:
                    from app.controllers.fer_controller import save_fer_rentabilidade_data_to_db
                    save_fer_rentabilidade_data_to_db(current_app, file_path)
                elif 'fer_patrimonio' in file_path:
                    from app.controllers.fer_controller import save_fer_patrimonio_data_to_db
                    save_fer_patrimonio_data_to_db(current_app, file_path)
                elif 'uff' in file_path:
                    from app.controllers.uff_controller import save_uff_to_db
                    save_uff_to_db(current_app, file_path)
                    
                return f'Upload realizado com sucesso. Arquivo salvo em: {file_path}', 200
            except Exception as e:
                current_app.logger.error(f"Erro ao salvar o arquivo: {e}")
                return f"Erro ao salvar o arquivo: {e}", 500

    return render_template('upload_siconfi.html')


    
@main.route('/download_next_report')
def download_next_report():
    download_next_focus_report()
    convert_all_pdfs()
    return redirect(url_for('main.index'))

@main.route('/anp')
def anp():
    data = fetch_anp_data()
    return render_template('anp.html', data=data) 


@main.route('/ibge')
def ibge():
    return render_template('ibge.html')

@main.route('/ibge/ipca')
def ibge_ipca():
    try:
        data, variable_options, unit_options, value_options = fetch_ipca_data()
        return render_template('ibge_ipca.html', data=data, variable_options=variable_options, unit_options=unit_options, value_options=value_options)
    except Exception as e:
        current_app.logger.error(f"Erro ao obter dados do IPCA: {str(e)}")
        return f"Erro ao obter dados do IPCA: {str(e)}"


@main.route('/ibge/unemployment')
def ibge_unemployment():
    try:
        data = fetch_unemployment_data()
        return render_template('ibge_unemployment.html', data=data)
    except Exception as e:
        current_app.logger.error(f"Erro ao obter dados de Desemprego: {str(e)}")
        return f"Erro ao obter dados de Desemprego: {str(e)}"
    
@main.route('/download_caged_data')
def download_caged_data_route():
    try:
        file_path = download_caged_data()
        return f'Download realizado com sucesso. Arquivo salvo em: {file_path}'
    except Exception as e:
        return f'Erro ao baixar o arquivo: {str(e)}'
    
@main.route('/focus')
def focus():
    return render_template('focus.html')

@main.route('/focus/selic')
def focus_selic():
    data = fetch_selic_data()
    return render_template('focus_selic.html', selic_data=data)

@main.route('/focus/ipca')
def focus_ipca():
    data = fetch_focus_ipca_data()
    return render_template('focus_ipca.html', data=data)

@main.route('/focus/cambio')
def focus_cambio():
    data = fetch_focus_cambio_data()
    return render_template('focus_cambio.html', data=data)

@main.route('/focus/pib')
def focus_pib():
    data = fetch_pib_data()
    return render_template('focus_pib.html', pib_data=data)

app/templates/anp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dados ANP</title>
</head>
<body>
    <h1>Dados ANP</h1>
    <table border="1">
        <thead>
            <tr>
                <th>Período</th>
                <th>Produto</th>
                <th>Nome do Produto</th>
                <th>Processo</th>
                <th>Nome do Processo</th>
                <th>Valor</th>
                <th>Unidades</th>
            </tr>
        </thead>
        <tbody>
            {% for item in data %}
            <tr>
                <td>{{ item['period'] }}</td>
                <td>{{ item['product'] }}</td>
                <td>{{ item['product-name'] }}</td>
                <td>{{ item['process'] }}</td>
                <td>{{ item['process-name'] }}</td>
                <td>{{ item['value'] }}</td>
                <td>{{ item['units'] }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/focus_cambio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Câmbio</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="./output.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #ccc;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
        }
    </style>
</head>
<body>
    <h1>Dados Câmbio</h1>
    <table>
        <thead>
            <tr>
                <th>Indicador</th>
                <th>Data</th>
                <th>Mediana</th>
                <th>Data Referência</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in data %}
            <tr>
                <td>{{ entry.Indicador }}</td>
                <td>{{ entry.Data }}</td>
                <td>{{ entry.Mediana }}</td>
                <td>{{ entry['Data Referência'] }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/focus_ipca.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IPCA</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="./output.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px 12px;
            border: 1px solid #ccc;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
        }
    </style>
</head>
<body>
    <h1>Dados IPCA</h1>
    <table>
        <thead>
            <tr>
                <th>Indicador</th>
                <th>Data</th>
                <th>Mediana</th>
                <th>Data Referência</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in data %}
            <tr>
                <td>{{ entry.Indicador }}</td>
                <td>{{ entry.Data }}</td>
                <td>{{ entry.Mediana }}</td>
                <td>{{ entry['Data Referência'] }}</td> 
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/focus_pib.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dados PIB</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Dados PIB</h1>

    {% if pib_data %}
    <div>
        <table>
            <thead>
                <tr>
                    <th>Indicador</th>
                    <th>Data</th>
                    <th>Mediana</th>
                    <th>Data Referência</th>
                </tr>
            </thead>
            <tbody>
                {% for item in pib_data %}
                <tr>
                    <td>{{ item.Indicador }}</td>
                    <td>{{ item.Data }}</td>
                    <td>{{ item.Mediana }}</td>
                    <td>{{ item['Data Referência'] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Não há dados disponíveis.</p>
    {% endif %}
</body>
</html>

app/templates/focus_selic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dados SELIC</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table, th, td {
            border: 1px solid black;
        }
        th, td {
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>Dados SELIC</h1>

    {% if selic_data %}
    <div>
        <table>
            <thead>
                <tr>
                    <th>Indicador</th>
                    <th>Data</th>
                    <th>Mediana</th>
                    <th>Data Referência</th> <!-- Nova coluna para mostrar a Data Referência -->
                </tr>
            </thead>
            <tbody>
                {% for item in selic_data %}
                <tr>
                    <td>{{ item.Indicador }}</td>
                    <td>{{ item.Data }}</td>
                    <td>{{ item.Mediana }}</td>
                    <td>{{ item['Data Referência'] }}</td> 
                </tr>
                {% endfor %}    
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Não há dados disponíveis.</p>
    {% endif %}
</body>
</html>

app/templates/ibge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IBGE</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            margin-bottom: 30px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 10px 0;
        }
        button:hover {
            background-color: #45a049;
        }
        .button-container {
            display: flex;
            flex-direction: row;
            align-items: flex-start;
            justify-content: center;
        }
        .button-space {
            margin: 5px;
        }
        .popup {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            background-color: #fff;
            border: 1px solid #ddd;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            z-index: 1000;
        }
        .popup.active {
            display: block;
        }
        .overlay {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0,0,0,0.5);
            z-index: 999;
        }
        .overlay.active {
            display: block;
        }
    </style>
</head>

<body>
    <h1>Dados do IBGE</h1>
    <a href="{{ url_for('main.ibge_ipca') }}"><button>IPCA</button></a>
    <a href="{{ url_for('main.ibge_unemployment') }}"><button>Desemprego</button></a>
    <a href="{{ url_for('main.download_caged_data_route') }}"><button>Postos de trabalho criados por setor</button></a>
</body>
</html>

app/templates/ibge_ipca.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IPCA</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
        .filter-select {
            width: 100%;
            padding: 8px;
            margin-bottom: 12px;
        }
    </style>
</head>
<body>
    <h1>Dados do IPCA</h1>
    <table id="ipcaTable">
        <thead>
            <tr>
                <th>
                    Variável<br>
                    <select id="variableFilter" class="filter-select">
                        <option value="">Todos</option>
                        {% for option in variable_options %}
                            <option value="{{ option }}">{{ option }}</option>
                        {% endfor %}
                    </select>
                </th>
                <th>
                    Unidade<br>
                    <select id="unitFilter" class="filter-select">
                        <option value="">Todos</option>
                        {% for option in unit_options %}
                            <option value="{{ option }}">{{ option }}</option>
                        {% endfor %}
                    </select>
                </th>
                <th>
                    Valor<br>
                    <select id="valueFilter" class="filter-select">
                        <option value="">Todos</option>
                        {% for option in value_options %}
                            <option value="{{ option }}">{{ option }}</option>
                        {% endfor %}
                    </select>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for item in data %}
                <tr>
                    <td>{{ item['D3C'] }}</td>
                    <td>{{ item['V'] }}</td>
                    <td>{{ item['D4N'] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const variableFilter = document.getElementById('variableFilter');
            const unitFilter = document.getElementById('unitFilter');
            const valueFilter = document.getElementById('valueFilter');
            const table = document.getElementById('ipcaTable').getElementsByTagName('tbody')[0];

            function filterTable() {
                const variableFilterValue = variableFilter.value.toLowerCase();
                const unitFilterValue = unitFilter.value.toLowerCase();
                const valueFilterValue = valueFilter.value.toLowerCase();

                for (const row of table.rows) {
                    const variableText = row.cells[0].textContent.toLowerCase();
                    const unitText = row.cells[1].textContent.toLowerCase();
                    const valueText = row.cells[2].textContent.toLowerCase();

                    row.style.display = 
                        (variableText.includes(variableFilterValue) &&
                        unitText.includes(unitFilterValue) &&
                        valueText.includes(valueFilterValue)) ? '' : 'none';
                }
            }

            variableFilter.addEventListener('change', filterTable);
            unitFilter.addEventListener('change', filterTable);
            valueFilter.addEventListener('change', filterTable);
        });
    </script>
</body>
</html>

app/templates/ibge_unemployment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Desemprego</title>
</head>
<body>
    <h1>Dados de Desemprego</h1>
    <table border="1">
        <tbody>
            {% for item in data %}
                <tr>
                    <td>{{ item['V'] }}</td>
                    <td>{{ item['D3C'] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/index.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Inicial</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="./output.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            margin-bottom: 30px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 10px 0;
        }
        button:hover {
            background-color: #45a049;
        }
        .button-container {
            display: flex;
            flex-direction: row;
            align-items: flex-start;
            justify-content: center;
        }

        .button-space{
            margin: 5px;
        }
    </style>
</head>
<body>
    <h1>Selecione a API</h1>

    <div class="button-container">

        <div class="button-space">
            <a href="{{ url_for('main.upload_siconfi') }}"><button>Upload SICONFI</button></a>
        </div>

        <div class="button-space">
            <a href="{{ url_for('main.focus') }}"><button>FOCUS</button></a>
        </div>
            
        <div class="button-space">
            <a href="{{ url_for('main.ibge') }}"><button>IBGE</button></a>
        </div>

        <div class="button-space">
            <a href="{{ url_for('main.anp') }}"><button>ANP</button></a>
        </div>


    </div>

</body>
</html> -->

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 flex items-center justify-center h-screen">
    <div class="w-full max-w-xs">
        <form method="POST" action="{{ url_for('auth.login') }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            <h2 class="text-2xl font-bold mb-6 text-center">Login</h2>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
                    Username
                </label>
                <input name="username" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Username">
            </div>
            <div class="mb-6">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
                    Password
                </label>
                <input name="password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="Password">
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Entrar
                </button> 
            </div>
        </form>
    </div>
</body>
</html>

app/templates/siconfi_bases.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Escolha o tipo de busca</title>
</head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            margin-bottom: 30px;
        }
        button {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin: 10px 0;
        }
        button:hover {
            background-color: #45a049;
        }
        .button-container {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }
    </style>
<body>
    
    <h1>Escolha o tipo de busca</h1>
    <div class="button-container">
        <a href="{{ url_for('main.siconfi_RREO') }}"><button>RREO</button></a>
    </div>
    <div class="button-container">
        <a href="{{ url_for('main.siconfi_RGF') }}"><button>RGF</button></a>
    </div>
</body>
</html>

app/templates/upload_siconfi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Siconfi RREO/RGF/FER/UFF</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="./output.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            background-color: #f4f4f9;
        }

        h1 {
            color: #333;
        }

        form {
            background: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            font-size: 1.1em;
            color: #333;
        }

        input[type="file"] {
            margin-top: 10px;
        }

        button {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        button:hover {
            background-color: #45a049;
        }

        .message {
            margin-top: 20px;
            padding: 10px;
            border-radius: 5px;
            display: none;
        }

        .success {
            background-color: #dff0d8;
            color: #3c763d;
        }

        .error {
            background-color: #f2dede;
            color: #a94442;
        }

        .loading {
            display: none;
            margin-top: 20px;
            padding: 10px;
            background-color: #8cb6e4;
            color: white;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <h1>Upload de Arquivo RREO/RGF/FER/UFF</h1>
    <form id="uploadForm" method="post" enctype="multipart/form-data">
        <label for="file">Selecione um arquivo:</label>
        <input type="file" name="file" id="file" required>
        <br>
        <button type="submit">Upload</button>
    </form>

    <div id="loadingMessage" class="loading">Aguarde, carregando planilha...</div>
    <div id="message" class="message"></div>

    <script>
        document.getElementById('uploadForm').addEventListener('submit', function(event) {
            event.preventDefault();

            var formData = new FormData(this);
            var xhr = new XMLHttpRequest();
            var loadingMessage = document.getElementById('loadingMessage');
            var messageDiv = document.getElementById('message');

            // Mostrar o pop-up azul
            loadingMessage.style.display = 'block';
            messageDiv.style.display = 'none';

            xhr.open('POST', '{{ url_for("main.upload_siconfi") }}', true);

            xhr.onload = function() {
                loadingMessage.style.display = 'none';  // Ocultar o pop-up azul
                if (xhr.status === 200) {
                    messageDiv.textContent = xhr.responseText;
                    messageDiv.className = 'message success';
                } else {
                    messageDiv.textContent = 'Erro ao fazer upload: ' + xhr.responseText;
                    messageDiv.className = 'message error';
                }
                messageDiv.style.display = 'block';
            };

            xhr.send(formData);
        });
    </script>
</body>
</html>